gcc-nvgpu:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  mpi:
    spec: cray-mpich
    gpu: cuda
  unify: true
  specs:
  - cmake
  - ninja
  - python
  - py-pandas
  - py-matplotlib
  - llvm@15.0.7 ~cuda ~flang ~gold ~ipo +link_llvm_dylib +lld ~lldb +llvm_dylib ~mlir ~libomptarget ~libomptarget_debug ~polly libunwind=none libcxx=none compiler-rt=none
  - mesa@22.1.6 +osmesa~glx+llvm
  - tbb
    #  - ospray
    #  We turn off hdf5 because vtk::hdf5 needs the internal hdf5 not the external one
  - paraview@5.12.0-RC1 +egl +cuda +mpi ~hdf5 +opengl2 +tbb +raytracing +python use_vtkm=on build_edition=rendering
  packages:
  - git
  - perl
  variants:
  - +cuda
  - cuda_arch=80
  - ~fortran
  - build_type=Release
  - cxxstd=17
  - ~examples

    #gcc-osmesa:
    #  compiler:
    #  - toolchain: gcc
    #    spec: gcc@11
    #  mpi:
    #    spec: cray-mpich
    #    gpu: cuda
    #  unify: true
    #  specs:
    #  - cmake
    #  - ninja
    #  - python
    #  - mesa+glx+llvm+opengl+osmesa swr=avx2 default_library=shared
    #  - vtk +osmesa ^mesa+glx+llvm+opengl+osmesa swr=avx2 default_library=shared
    #  - paraview@5.11.2+osmesa~cuda+mpi+opengl2+tbb +raytracing +python use_vtkm=default build_edition=rendering ^mesa+glx+llvm+opengl+osmesa swr=avx2 default_library=shared
    #  packages:
    #  - git
    #  - perl
    #  - diffutils
    #  - gettext
    #  - openssh
    #  - openssl
    #  - ncurses
    #  - cpio
    #  variants:
    #  - ~fortran
    #  - build_type=Release
    #  - cxxstd=17
    #  - ~examples
