# Example use:
# cd $SRC/alps-vcluster/alps-uenv/recipes/jbdev
# eiger
# python ../generator/generate_recipe.py -m mpich -c gcc -C eiger -r jbdev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C eiger -r jbdev -t ./templates -o ./ompi
# daint
# python ../generator/generate_recipe.py -m mpich -c gcc -C daint -r jbdev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C daint -r jbdev -t ./templates -o ./ompi
#
# copy to alps
# /home/biddisco/src/alps-vcluster/upalps.sh

${ENVNAME}:

  views:
    develop:
      # Exclude gcc-runtime to avoid adding a copy of libgomp.so to the view
      exclude: [gcc-runtime]
      link: all
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]

  unify: true

  compiler=gcc:
    compiler: [gcc]
  compiler=llvm:
    compiler: [llvm]
  compiler=gcc-llvm:
    compiler: [gcc, llvm]

  network:
    # ---------------
    # mpich
    # ---------------
    mpi=mpich:
      cluster=eiger:
        mpi: cray-mpich@8.1.32
        specs: ['libfabric@2.3.1']
      cluster=oryx:
        mpi: mpich +cuda
      cluster=else:
        mpi: cray-mpich@9 +cuda
        specs:
        - libfabric       @git.cbcabd6590bcbbbde7beca1dbd1e9076b5411ffb=main +gdrcopy fabrics=lnx,cxi,rxm,tcp,shm   
        - cassini-headers @git.4d2c6845ae99f70ebc4b96e6a82b20989cc6bfaf=main
        - cxi-driver      @git.6d61eeb23a7cf0c56b8043dfe89f341119cdb86b=main
        - libcxi          @git.4fac509ba8f1494d4a52fbfd9343bdd4b54cfadc=main
             
    # ---------------
    # openmpi
    # ---------------
    mpi=ompi:
      cluster=eiger:
        specs: ['openmpi@git.v5.0.x=main']
      cluster=else:
        mpi: openmpi@git.v5.0.x=main +cuda +continuations fabrics=cma,ofi,xpmem schedulers=slurm +internal-pmix +cray-xpmem
        specs: 
        - libfabric       @git.cbcabd6590bcbbbde7beca1dbd1e9076b5411ffb=main +gdrcopy fabrics=lnx,cxi,rxm,tcp,shm   
        - cassini-headers @git.4d2c6845ae99f70ebc4b96e6a82b20989cc6bfaf=main
        - cxi-driver      @git.6d61eeb23a7cf0c56b8043dfe89f341119cdb86b=main
        - libcxi          @git.4fac509ba8f1494d4a52fbfd9343bdd4b54cfadc=main

  packages:
  - git
  - perl
  - libtool

  specs:
  - libtool@2.4.6
  - bash@5.2

  # ----------
  # Build + repo tools
  # ----------
  - cmake@4 # cmake 3.29+ introduced a cupti bug, use 4.x
  - ninja
  - direnv
  - libtree

  # ----------
  # sys tools
  # ----------
  - hwloc

  # ----------
  # mpi tools
  # ----------
  - osu-micro-benchmarks

  # ----------
  # runtime/framework
  # ----------
  - kokkos +openmp

  # ----------
  # C++ libraries
  # ----------
  - fmt
  - stdexec@git.nvhpc-25.03.rc1=main
  - boost
    +atomic +chrono +container +context +coroutine +filesystem +iostreams +json +multithreaded
    +program_options +regex +serialization +shared +system +test +thread +timer ~mpi

  # ----------
  # IO/files
  # ----------
  - hdf5 +mpi +cxx +hl +szip +shared
  - h5hut@master
  - nlohmann-json

  # ----------
  # maths
  # ----------
  - gsl
  - fftw
  - heffte@develop ~python +fftw
  - eigen
  - blaspp
  - lapackpp

  # ----------
  # allocators/memory management
  # ----------
  - mimalloc   +skip_collect_on_exit
  - umpire     ~shared ~mpi

  # ----------
  # debugging/profiling/testing/logging
  # ----------
  - gdb
  - hpctoolkit@git.2025.0.1=develop
  - dyninst@master
  - elfutils ~debuginfod
  - "libunwind@1.8.1:"

  - papi
  - gperftools
  - googletest
  - protobuf
  - spdlog

# ----------
  - arch=gh200:
    # GPU support
    - cuda@12.8
    - whip@main

    # Viz
    # - ascent@develop +cuda +vtkh +python +occa +mfem 
    # - conduit@develop

    # Maths
    - nvpl-blas
    - nvpl-lapack
    - nvpl-fft

# ----------
  - arch=zen2:
    # Maths
    #- intel-oneapi-mkl
    - openblas

# ----------
  - arch=ada:
    # GPU support
    - cuda
    - whip@main

    # Maths
    - intel-oneapi-mkl

  variants:
  - build_type=Release
  - cxxstd=20
  - ~fortran
  - ~examples
  - ~tests
  - ~testing
  - +mpi
  - +cxx
  - +python

# ----------
  - arch=gh200:
    - +cuda
    - cuda_arch=90
   # - +cuda_uvm
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl

# ----------
  - arch=zen2:
    - ~cuda
    - ~x11
    - ^[virtuals=blas,lapack] intel-oneapi-mkl

# ----------
  - arch=ada:
    - +cuda
    - cuda_arch=89
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl
