# Example use:
# cd $SRC/alps-vcluster/alps-uenv/recipes/jbdev
# eiger
# python ../generator/generate_recipe.py -m mpich -c gcc -C eiger -r jbdev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C eiger -r jbdev -t ./templates -o ./ompi
# daint
# python ../generator/generate_recipe.py -m mpich -c gcc -C daint -r jbdev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C daint -r jbdev -t ./templates -o ./ompi
#
# copy to alps
# /home/biddisco/src/alps-vcluster/upalps.sh

${ENVNAME}:

  views:
    develop:
      exclude: []
      link: all
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]

  unify: true

  compiler=gcc:
    compiler: [gcc]
  compiler=llvm:
    compiler: [llvm]
  compiler=gcc+llvm:
    compiler: [gcc, llvm]

  mpi:
    # ---------------
    # mpich
    # ---------------
    mpi=mpich:
      cluster=eiger:
        spec: cray-mpich@9
        gpu: null
        depends:
        - cassini-headers @git.59b6de6a91d9637809677c50cc48b607a91a9acb=main
        - cxi-driver      @git.08deb056fac4ca8b0d3d39b5f7cc0dad019ee266=main
        - libcxi          @git.be1f7149482581ad589a124e5f6764b9d20d2d45=main
        - libfabric       @git.v2.2.0=main fabrics=lnx,cxi,rxm,tcp,shm
      cluster=oryx:
        spec: mpich
        gpu: cuda
      cluster=else:
        spec: cray-mpich@9
        gpu: cuda
        xspec: +cxi
        depends:
        - cassini-headers @git.59b6de6a91d9637809677c50cc48b607a91a9acb=main
        - cxi-driver      @git.08deb056fac4ca8b0d3d39b5f7cc0dad019ee266=main
        - libcxi          @git.be1f7149482581ad589a124e5f6764b9d20d2d45=main
        - libfabric       @git.v2.2.0=main +gdrcopy fabrics=lnx,cxi,rxm,tcp,shm

    # ---------------
    # openmpi
    # ---------------
    mpi=ompi:
      cluster=eiger:
        spec: openmpi@git.v5.0.x=main
        xspec: +continuations +internal-pmix fabrics=cma,ofi,xpmem schedulers=slurm +cray-xpmem
        gpu: null
        depends:
        - cassini-headers @git.59b6de6a91d9637809677c50cc48b607a91a9acb=main
        - cxi-driver      @git.08deb056fac4ca8b0d3d39b5f7cc0dad019ee266=main
        - libcxi          @git.be1f7149482581ad589a124e5f6764b9d20d2d45=main
        - libfabric       @git.v2.2.0=main fabrics=lnx,cxi,rxm,tcp,shm
      cluster=oryx:
        spec: openmpi@git.v5.0.x=main
        gpu: cuda
      cluster=else:
        spec: openmpi@git.v5.0.x=main
        gpu: cuda
        xspec: +continuations +internal-pmix fabrics=cma,ofi,xpmem schedulers=slurm +cray-xpmem
        depends:
        - cassini-headers @git.59b6de6a91d9637809677c50cc48b607a91a9acb=main
        - cxi-driver      @git.08deb056fac4ca8b0d3d39b5f7cc0dad019ee266=main
        - libcxi          @git.be1f7149482581ad589a124e5f6764b9d20d2d45=main
        - libfabric       @git.v2.2.0=main +gdrcopy fabrics=lnx,cxi,rxm,tcp,shm

  packages:
  - git
  - perl
  - libtool

  specs:

  # - pika@main
  # - dla-future@master

  - libtool@2.4.6
  - bash@5.2

  # ----------
  # Build + repo tools
  # ----------
  - cmake@4
  - ninja
  - direnv
  - libtree

  # ----------
  # sys tools
  # ----------
  - hwloc

  # ----------
  # mpi tools
  # ----------
  - osu-micro-benchmarks

  # ----------
  # c++ helpers
  # ----------
  - fmt
  - stdexec@main
  - boost
    +atomic +chrono +container +context +coroutine +filesystem +iostreams +json +multithreaded
    +program_options +regex +serialization +shared +system +test +thread +timer ~mpi

  # ----------
  # runtime/framework
  # ----------
  - kokkos +openmp

  # ----------
  # IO/files
  # ----------
  - hdf5 +mpi +cxx +hl +szip +shared
  - h5hut@master
  - nlohmann-json

  # ----------
  # maths
  # ----------
  - gsl
  - fftw
  - heffte@develop ~python
  - eigen
  - blaspp@2024.10.26
  - lapackpp@2024.10.26

  # ----------
  # allocators/memory management
  # ----------
  - mimalloc   +skip_collect_on_exit
  - umpire     ~shared ~mpi

  # ----------
  # debugging/profiling/testing/logging
  # ----------
  - gdb
  - hpctoolkit@develop
  - dyninst@master
  - elfutils ~debuginfod
  - "libunwind@1.8.1:"

  - papi
  - gperftools
  - googletest
  - protobuf
  - spdlog

  - arch=gh200:
    # GPU support
    - cuda@12.8
    - whip@main

    # Maths
    - nvpl-blas
    - nvpl-lapack
    - nvpl-fft

  - arch=zen2:
    # Maths
    - intel-oneapi-mkl
    - openblas

  - arch=ada:
    # GPU support
    - cuda
    - whip@main

    # Maths
    - intel-oneapi-mkl

  variants:
  - build_type=Release
  - cxxstd=20
  - ~fortran
  - ~examples
  - ~tests
  - ~testing
  - +mpi
  - +cxx
  - +python

  - arch=gh200:
    - +cuda
    - cuda_arch=90
   # - +cuda_uvm
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl

  - arch=zen2:
    - ~cuda
    - ~x11

  - arch=ada:
    - +cuda
    - cuda_arch=89
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl
