substitutions:
  environment:
      mc:
        gcc:
          mpich: paraview-mc-gcc-mpich
        openmpi: paraview-mc-gcc-openmpi
      gh200:
        gcc:
          mpich: paraview-gh200-gcc-mpich
          openmpi: paraview-gh200-gcc-openmpi
