name: ${ENVNAME}
version: 2
spack:
  commit: v1.1.0
  repo: https://github.com/biddisco/spack.git
  packages:
    commit: 1a32c3379c9fa28549c68b7931712d81831304df # misc-fixes
    repo: https://github.com/biddisco/spack-packages # https://github.com/spack/spack-packages.git
store: /user-environment
description: opal-x tools
modules: false
