${ENVNAME}:

  views:
    default-llvm:
      link: roots
      exclude: ["llvm-amdgpu"]
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
    default:
      link: roots
      exclude: ["llvm"]
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
                    
  unify: when_possible
  duplicates:
    strategy: full

  compiler=gcc:
    compiler: [gcc]
  compiler=llvm:
    compiler: [llvm]
  compiler=gcc-llvm:
    compiler: [gcc, llvm-amdgpu]

  network:
    # ---------------
    # mpich
    # ---------------
    mpi=mpich:
      cluster=eiger:
        mpi: cray-mpich@8.1.32
        specs:
        - libfabric       @main fabrics=cxi,rxm,tcp,shm,xpmem
        - cassini-headers @git.release/shs-13.0=main
        - cxi-driver      @git.release/shs-13.0=main
        - libcxi          @git.release/shs-13.0=main
      cluster=oryx:
        mpi: mpich +cuda
      cluster=beverin:
        mpi: mpich +rocm amdgpu_target=gfx942 netmod=ofi ~fortran +slurm pmi=pmi2
        specs:
        - libfabric       @2.3.1 fabrics=cxi,rxm,tcp,rxd,udp +rocm amdgpu_target=gfx90a,gfx942
        - cassini-headers @git.release/shs-13.0=main
        - cxi-driver      @git.release/shs-13.0=main
        - libcxi          @git.release/shs-13.0=main
      cluster=else:
        mpi: cray-mpich@9 +cuda
        specs:
        - libfabric       @main +gdrcopy fabrics=lnx,cxi,rxm,tcp,shm,xpmem
        - cassini-headers @git.release/shs-13.0=main
        - cxi-driver      @git.release/shs-13.0=main
        - libcxi          @git.release/shs-13.0=main
             
    # ---------------
    # openmpi
    # ---------------
    mpi=ompi:
      cluster=eiger:
        mpi: openmpi@git.v5.0.10 ~cuda fabrics=cma,ofi,xpmem schedulers=slurm +internal-pmix +cray-xpmem
        specs:
        - libfabric       @main fabrics=cxi,rxm,tcp,shm,xpmem
        - cassini-headers @git.release/shs-13.0=main
        - cxi-driver      @git.release/shs-13.0=main
        - libcxi          @git.release/shs-13.0=main
      cluster=else:
        mpi: openmpi@5.0.8 +cuda fabrics=cma,ofi,xpmem schedulers=slurm +internal-pmix +cray-xpmem
        specs: 
        - libfabric       @main +gdrcopy fabrics=lnx,cxi,rxm,tcp,shm,xpmem
        - cassini-headers @git.release/shs-13.0=main
        - cxi-driver      @git.release/shs-13.0=main
        - libcxi          @git.release/shs-13.0=main

  specs:
  # ----------
  # Build + repo tools
  # ----------
  - cmake
  - ninja
  - direnv

  # ----------
  # sys tools
  # ----------
  - hwloc

  # ----------
  # mpi tools
  # ----------
#  - osu-micro-benchmarks ~xccl

  # ----------
  # runtime/framework
  # ----------
  - kokkos@4.7 ~openmp +pic 

  # ----------
  # C++ libraries
  # ----------
  - boost +atomic +chrono +container +context +coroutine +filesystem +iostreams +json 
    +multithreaded +program_options +regex +serialization +shared +system +test +thread 
    +timer

  # ----------
  # IO/files
  # ----------
  - hdf5 +mpi +cxx +hl +szip +shared
  - h5hut@master

  # ----------
  # maths
  # ----------
  - gsl
  - fftw
  - heffte@2.4.1 ~python ~fftw
  - eigen
  - blaspp@2024.10.26
  - lapackpp@2024.10.26
  - openblas threads=openmp

  # ----------
  # profiling/debugging/testing
  # ----------
  - papi
  - gperftools
  - googletest

  # ----------
  # logging/formatting
  # ----------
  - spdlog
  - fmt
  
  # ----------
  # viz support
  # ----------
#  - conduit +python +mpi +hdf5
#  - libcatalyst +mpi +python
  # - ascent@develop +python ~adios2 ~vtkh ~raja ~umpire
    # - adios2 +hdf5 +mpi ~zfp ~mgard

  - arch=mi300:
    # ------------------------------------------
    # hip @ 7
    # ------------------------------------------
    # add GPU-specific packages here, for easier comparison with mc version
    - hip@6 ^mesa@23.3.6
    - hdf5+mpi
    - hipcub
    - llvm-amdgpu
    # rocm packages
    - rocblas ^py-msgpack %cxx=gcc
    - rocfft
    - rocm-cmake %cxx=gcc
    - rocm-openmp-extras
    - rocm-core %cxx=gcc
    - rocminfo
    - rocprim
    - rocprofiler-dev
    - rocprofiler-sdk
    - rocprof-trace-decoder
    - rocprofiler-systems +internal-dyninst+internal-boost+trace-decoder
    - rocprofiler-compute
    - rocrand
    - rocsolver
    - rocsparse
    - rocthrust
    - roctracer-dev-api %cxx=gcc
    - roctracer-dev
    - rocm-gdb
    - rocm-debug-agent
    # - hsa-rocr-dev # TODO(iomaganaris): enable for julia AMD gpu build
    # hip packages
    - hipblas
    - hipblaslt
    - hiprand
    - hipsparse~shared-libs
    - hipfft
    - hipblas-common
    # - miopen-hip  # TODO(iomaganaris): enable for julia AMD gpu build
    # networking
    - rccl
    # commits pinned for reproducibility, not bugs; update when updating recipe
    - aws-ofi-rccl@git.6dae1b0d588c27689ba6daa32710359ea96de78c=cxi
    - rccl-tests@git.6405c76e6826663bbb67bd40aeee8c70aa5d3094=develop %cxx=llvm-amdgpu ^mpich +rocm netmod=ofi ~fortran +slurm pmi=pmi2
    #^cray-mpich@8.1.32 +rocm %c,cxx,fortran=gcc

    # ------------------------------------------
    # hip @ 7
    # ------------------------------------------
    # - hip@7.1.0 ^mesa@23.3.6
    # - rocprofiler-dev
    # - rocprofiler-systems@7 +internal-dyninst+internal-boost
    # - rocprofiler-compute

     
  - arch=gh200:
    # NVidia GPU support
    - cuda@12.9.0
    - cufftmp@11.4.0 # needs cuda @12.9
    # - nccl-tests
    # - aws-ofi-nccl
    - nvshmem +mpi +cuda +nccl +libfabric +gdrcopy ~ucx
    - nccl@2.27
    - cublasmp
    - cusolvermp

    # ----------
    # debugging/profiling/testing/logging
    # ----------
    # - hpctoolkit@2025.0.1 ~python
    # - dyninst@master
    # - elfutils ~debuginfod
    # - "libunwind@1.8.1:"
    - cmake@4 # cmake 3.29+ introduced a cupti bug, use 4.x

  - arch=zen2:
    # Maths
    - intel-oneapi-mkl
    - openblas

  - arch=ada:
    # GPU support
    - cuda@12
    - whip@main

    # Maths
    - intel-oneapi-mkl

  variants:
  - build_type=Release
  - cxxstd=20
  - ~fortran
  - ~examples
  - ~tests
  - ~testing
  - +mpi
  - +cxx
  - +python

  - arch=mi300:
    # GPU support
    - ~cuda
    - +rocm
    - +apu
    - amdgpu_target=gfx942          # ,gfx90a kokkos only allows one arch
    - amdgpu_target_sram_ecc=gfx942 # ,gfx90a
    - +wrapper
    - ~x11
    - ~adios2
    - ~zfp
#    - ^python@3.12.12
    - ^[virtuals=gl] egl
  
  - arch=gh200:
    - +cuda
    - cuda_arch=90
    - +mpi_gpu_aware
      # - +cuda_uvm
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl

  - arch=zen2:
    - ~cuda
    - ~x11

  - arch=ada:
    - +cuda
    - cuda_arch=89
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl
