name: icon-cmake
store: /user-environment
spack:
  commit: jb-develop
  #repo: /home/biddisco/opt/spack.git
  repo: /capstor/scratch/cscs/biddisco/spack-todi
description: The tools required to build ICON blue line using cmake
modules: false

