icon-dsl-paraview:
  compiler:
    - toolchain: gcc
      spec: gcc
    - toolchain: llvm
      spec: nvhpc
  unify: when_possible
  mpi:
    spec: cray-mpich@8.1.29%nvhpc
    gpu: cuda
  specs:
    # CUDA and python
    - cuda@12.3                       %gcc
    - python@3.10                     %gcc

    # icon support : compile all fortran enabled packages using nvhpc
    - hdf5                  %nvhpc +fortran +hl
    - libcatalyst@2.0.0     %nvhpc +fortran +mpi +python
    - eccodes@2.34.0        %nvhpc +fortran +aec +tools +openmp +shared jp2k=jasper
    - libcdi-pio@develop    %nvhpc +fortran +mpi ~external-grib1+netcdf+shared~szip-grib1+threads  grib2=eccodes
    - netcdf-fortran@4.6.1  %nvhpc ~doc+pic +shared
    - serialbox@2.6.1       %nvhpc +fortran +async-api+c~examples~ftg~ipo+logging~netcdf~python~sdb~shared+std-filesystem
    - yaxt@0.9.3.1          %nvhpc +fortran +shared
    - mtime@master          %nvhpc
    - rte-rrtmgp@autoconf   %nvhpc
    
    # c2sm/icon dependencies that don't need fortran compilation, use gcc
    - libfyaml@0.8          %gcc
    - libxml2@2.10.3        %gcc +pic~python+shared
    - netcdf-c@4.9.2        %gcc +blosc ~byterange ~dap ~fsync ~hdf4 ~jna +mpi ~nczarr_zip +optimize +parallel-netcdf +pic +shared +szip +zstd
    - perl@5.38.0           %gcc +cpanm +opcode +open +shared +threads

    # Icon python packages we are currently installing manually
    # - py-gridtools-cpp@2.3.2        %gcc@12.3.0
    # - py-gt4py@main
    # - py-icon4py@main                %gcc@12.3.0

    # everything needed for nccl on SS11 (from Ben's setup)
    - aws-ofi-nccl@master%gcc
    - nccl%gcc
    - nccl-tests%gcc

    # Build + repo tools
    - cmake@3.27                      %gcc
    - git-lfs                         %gcc
    - ninja                           %gcc
    - direnv                          %gcc
    - libtree                         %gcc
    - llvm@14                         %gcc ~gold ~cuda

    # maths
    - blaspp                          %gcc
    - eigen                           %gcc
    - fftw                            %gcc
    - lapackpp                        %gcc
    - openblas                        %gcc
    - proj                            %gcc

    # c++ helpers
    - fmt                             %gcc
    - stdexec@main                    %gcc

    # IO and parallelism
    - h5hut@master                    %gcc
    - lz4                             %gcc

    # memory management
    - jemalloc                        %gcc
    - mimalloc                        %gcc

    # profiling/testing
    - gperftools                      %gcc
    - googletest                      %gcc

    # vtk external deps
    - cgns@4.4.0                      %gcc
    - double-conversion@3.3.0         %gcc
    - gl2ps                           %gcc
    - glew                            %gcc gl=egl
    - jpeg                            %gcc
    - jsoncpp                         %gcc
    - libharu                         %gcc
    - libtiff                         %gcc
    - nlohmann-json                   %gcc
    - libtheora@master                %gcc
    - pugixml                         %gcc
    - protobuf@:3.21                  %gcc # protobuf@3.4 - 3.21 to prevent abseil being pulled in @3.22:
    - seacas                          %gcc
    - utf8cpp                         %gcc

    # ParaView python
    - py-pandas                       %gcc
    - py-matplotlib                   %gcc
    - py-mpi4py                       %gcc

    # The following are required to stop spack from using nvhpc to build
    # basic dependencies, some of which don't compile with nvc etc.
    - autoconf                        %gcc
    - automake                        %gcc
    - ca-certificates-mozilla         %gcc
    - diffutils                       %gcc
    - gnuconfig                       %gcc
    - libiconv                        %gcc
    - libxcrypt                       %gcc
    - m4                              %gcc
    - ncurses                         %gcc
    - openssl                         %gcc
    - xz                              %gcc
    - zlib                            %gcc
    - zstd                            %gcc
    - c-blosc                         %gcc
    - libaec                          %gcc
    - jasper                          %gcc
    - patchelf                        %gcc
    - gmake                           %gcc

  variants:
    - build_type=Release
    - +cuda
    - cuda_arch=90
    - +mpi
    - gl=egl
    - ~x11
    - ~examples
    - +fortran
  packages:
    - curl
    - gmake
  views:
    default:
