icon-dsl-paraview:
  compiler:
      - toolchain: gcc
        spec: gcc
      - toolchain: llvm
        spec: nvhpc
  unify: true
  mpi:
      spec: cray-mpich@8.1.29%nvhpc 
      gpu: cuda

  variants:
  - build_type=Release
  - +cuda
  - cuda_arch=90
  - +mpi
  - ~x11
  - ~examples
  - +fortran

  packages:
  - curl
  - gmake
  
  views:
    default:

  specs:
    # CUDA and python
    - cuda@12.3                       
    - python@3.10                     

    # icon support : compile all fortran enabled packages using nvhpc
    - hdf5                  %nvhpc +fortran +hl
    - libcatalyst@2.0.0     %nvhpc +fortran +mpi +python 
    # +conduit
    - ecrad@git.31bf864f84d87219d87bbc558e0bc9fdda33df88=develop %nvhpc 
    - eccodes@2.34.0        %nvhpc +fortran +aec +tools +openmp +shared jp2k=jasper
    - libcdi-pio@develop    %nvhpc +fortran +mpi ~external-grib1+netcdf+shared~szip-grib1+threads grib2=eccodes ^eccodes+openmp
    - netcdf-fortran@4.6.1  %nvhpc ~doc+pic +shared
    - serialbox@2.6.1       %nvhpc +fortran +async-api+c~examples~ftg~ipo+logging~netcdf~python~sdb~shared+std-filesystem
    - yaxt@0.9.3.1          %nvhpc +fortran +shared
    - mtime@master          %nvhpc
    - rte-rrtmgp@autoconf   %nvhpc
    # - yac                   %nvhpc
    
    # c2sm/icon dependencies that don't need fortran compilation, can use gcc
    - libfyaml@0.8          
    - libxml2@2.10.3         +pic~python+shared
    - netcdf-c@4.9.2         +blosc ~byterange ~dap ~fsync ~hdf4 ~jna +mpi ~nczarr_zip +optimize +parallel-netcdf +pic +shared +szip +zstd
    - perl@5.38.0            +cpanm +opcode +open +shared +threads

    # Icon python packages we are currently installing manually
    # - py-gridtools-cpp@2.3.2        @12.3.0
    # - py-gt4py@main
    # - py-icon4py@main                @12.3.0

    # everything needed for nccl on SS11 (from Ben's setup)
    # - aws-ofi-nccl@master
    # - nccl
    # - nccl-tests

    # Build + repo tools
    - cmake                      
    - git-lfs                         
    - ninja                           
    - direnv                          
    - libtree                         
    - llvm                              

    # maths
    - eigen                           
    - fftw                            
    - proj                            
    - nvpl-blas                        threads=none
    - nvpl-lapack                      threads=none
    - blaspp                           ~openmp ~cuda
    - openblas                        
    - lapackpp                        

    # CUDA/HIP support
    - whip@main                       

    # c++ helpers
    - fmt                             
    - stdexec@git.b39a506096900de4074ee556867a3805bd8351bd=main 
    - boost                            +atomic +container +context +coroutine +json +multithreaded +program_options +serialization +shared +system +test +thread

    # IO and parallelism
    - h5hut@master                    
    - lz4                             
    - libxml2                         

    # memory management
    - jemalloc                        
    - mimalloc                        

    # profiling/testing
    - gperftools                      
    - googletest                      

    # vtk external deps
    - cgns@develop                     ~fortran 
    - seacas                           ~fortran ~applications ~legacy ~tests ~x11
    - double-conversion@3.3.0         
    - gl2ps                           
    - glew                            
    - jpeg                            
    - jsoncpp                         
    - libharu                         
    - libtiff                         
    - nlohmann-json                   
    - libtheora@master                
    - pugixml                         
    - protobuf@:3.21                   # protobuf@3.4 - 3.21 to prevent abseil being pulled in @3.22:
    - utf8cpp                         

    # ParaView python
    - py-pandas                       
    - py-matplotlib                   
    - py-mpi4py
    - py-numpy                       
