name: ${ENVNAME}
version: 2
spack:
  commit: develop
  repo: https://github.com/biddisco/spack.git
  packages:
    commit: develop
    repo: https://github.com/spack/spack-packages.git
store: /user-environment
description: JB-Dev environment
modules: false
