# Example use:
# cd $SRC/alps-vcluster/alps-uenv/recipes/jb-dev
# eiger
# python ../generator/generate_recipe.py -m mpich -c gcc -C eiger -r jb-dev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C eiger -r jb-dev -t ./templates -o ./ompi
# daint
# python ../generator/generate_recipe.py -m mpich -c gcc -C daint -r jb-dev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C daint -r jb-dev -t ./templates -o ./ompi


${ENVNAME}:

  views:
    develop:
      exclude: []
      link: all
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]

  unify: true

  compiler:
    compiler=gcc:
      - toolchain: gcc
        spec: gcc@13
    compiler=llvm:
      - toolchain: llvm
        spec: nvhpc
    compiler=gcc+llvm:
      - toolchain: gcc
        spec: gcc@12
      - toolchain: llvm
        spec: nvhpc

  mpi:
    mpi=mpich:
      cluster=eiger:
        spec: cray-mpich@8.1.30
        gpu: null
        depends: [libfabric@main]
      cluster=oryx:
        spec: laptop-mpich
        gpu: cuda
      cluster=else:
        spec: cray-mpich@8.1.32
        gpu: cuda
        depends: [libfabric@main]
    mpi=ompi:
      spec: openmpi@git.mpi-continue-5.0.6=main
      xspec: +continuations +internal-pmix fabrics=cma,ofi,xpmem schedulers=slurm +cray-xpmem
      gpu: null
      depends: ["libfabric@git.lnx_refactor_main=main fabrics=lnx,cxi,rxm,tcp,shm"]

  packages:
  - git
  - perl

  specs:
  # Build + repo tools
  - cmake
  - ninja
  - git-lfs
  - direnv
  - libtree

  # sys tools
  - hwloc

  # mpi tools
  - osu-micro-benchmarks

  # c++ helpers
  - fmt
  - stdexec@24.09
  - boost             ~mpi +atomic +chrono +container +context +coroutine +filesystem +iostreams +json +multithreaded +program_options +regex +serialization +shared +system +test +thread +timer
  - kokkos

  # IO
  - hdf5 +mpi +cxx +hl +szip +shared
  - h5hut@master

  # maths
  - eigen
  - fftw
  - proj
  - blaspp@2024.10.26
  - lapackpp@2024.10.26
  - heffte

  # allocators/memory management
  - mimalloc         +skip_collect_on_exit
  - umpire@2024.07.0 ~shared ~mpi

  # profiling/testing/logging
  - papi
  - gperftools
  - googletest
  - protobuf
  - spdlog

  - arch=gh200:
    # CUDA/HIP support
    - cuda
    - whip@main

    # Maths
    - nvpl-blas
    - nvpl-lapack
    - nvpl-fft
    - gsl

  - arch=zen2:
    # Maths
    - intel-oneapi-mkl
    - openblas

  - arch=ada:
    # CUDA
    - cuda
    - whip@main

    # Maths
    - intel-oneapi-mkl

  variants:
  - build_type=Release
  - cxxstd=20
  - ~fortran
  - ~examples
  - ~tests
  - ~testing
  - +mpi
  - +cxx
  - +python

  - arch=gh200:
    - +cuda
    - cuda_arch=90
   # - +cuda_uvm
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl

  - arch=zen2:
    - ~cuda
    - ~x11

  - arch=ada:
    - +cuda
    - cuda_arch=89
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl
