# Example use:
# cd $SRC/alps-vcluster/alps-uenv/recipes/jb-dev
# eiger
# python ../generator/generate_recipe.py -m mpich -c gcc -C eiger -r jb-dev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C eiger -r jb-dev -t ./templates -o ./ompi
# daint
# python ../generator/generate_recipe.py -m mpich -c gcc -C daint -r jb-dev -t ./templates -o ./mpich
# python ../generator/generate_recipe.py -m ompi  -c gcc -C daint -r jb-dev -t ./templates -o ./ompi
#
# copy to alps
# /home/biddisco/src/alps-vcluster/upalps.sh

${ENVNAME}:

  views:
    develop:
      exclude: []
      link: all
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]

  unify: true

  compiler:
    compiler=gcc:
      - toolchain: gcc
        spec: gcc@13
    compiler=llvm:
      - toolchain: llvm
        spec: nvhpc
    compiler=gcc+llvm:
      - toolchain: gcc
        spec: gcc@12
      - toolchain: llvm
        spec: nvhpc

  mpi:
    mpi=mpich:
      cluster=eiger:
        spec: cray-mpich@8.1.30
        gpu: null
        depends: [libfabric@main]
      cluster=oryx:
        spec: mpich
        gpu: cuda
      cluster=else:
        spec: cray-mpich@8.1.32
        gpu: cuda
        xspec: +cxi
        depends:
        # latest commit 5b6fd6e0efa770c8928fbc8a00e782b5a843c890 (HEAD -> lnx_refactor_main, amir/lnx_refactor_main)
        - libfabric@git.lnx_refactor_main=main fabrics=lnx,cxi,rxm,tcp,shm
        - cxi-driver@main
        - libcxi@main
        - cassini-headers@main
    mpi=ompi:
      # spec: openmpi@git.mpi-continue-5.0.6=main
      # xspec: +continuations +internal-pmix fabrics=cma,ofi,xpmem schedulers=slurm +cray-xpmem
      spec: openmpi@git.d8338575e4f4888ba01d9bc00e514df3c126d0c9=main
      xspec: +continuations +internal-pmix fabrics=cma,ofi,xpmem schedulers=slurm +cray-xpmem
        # ~debug dev_path=/capstor/scratch/cscs/biddisco/src/openmpi
      gpu: cuda
      depends:
      - libfabric@git.lnx_refactor_main=main fabrics=lnx,cxi,rxm,tcp,shm dev_path=/capstor/scratch/cscs/biddisco/src/libfabric
        # ~debug
      - cxi-driver@main dev_path=/capstor/scratch/cscs/biddisco/src/cxi-driver
      - libcxi@main dev_path=/capstor/scratch/cscs/biddisco/src/libcxi
      - cassini-headers@main dev_path=/capstor/scratch/cscs/biddisco/src/cassini-headers

  packages:
  - git
  - perl

  specs:

  # - pika@main
  # - dla-future@master

  # ----------
  # Build + repo tools
  # ----------
  - cmake
  - ninja
  - direnv
  - libtree

  # ----------
  # sys tools
  # ----------
  - hwloc

  # ----------
  # mpi tools
  # ----------
  - osu-micro-benchmarks

  # ----------
  # c++ helpers
  # ----------
  - fmt
  - stdexec@git.nvhpc-25.03.rc1=main
  - boost
    +atomic +chrono +container +context +coroutine +filesystem +iostreams +json +multithreaded
    +program_options +regex +serialization +shared +system +test +thread +timer ~mpi

  # ----------
  # runtime/framework
  # ----------
  - kokkos +openmp

  # ----------
  # IO/files
  # ----------
  - hdf5 +mpi +cxx +hl +szip +shared
  - h5hut@master
  - nlohmann-json

  # ----------
  # maths
  # ----------
  - gsl
  - fftw
  - heffte@git.9eab7c0eb18e86acaccc2b5699b30e85a9e7bdda=2.4.1
  - eigen
  - blaspp@2024.10.26
  - lapackpp@2024.10.26

  # ----------
  # allocators/memory management
  # ----------
  - mimalloc   +skip_collect_on_exit
  - umpire     ~shared ~mpi

  # ----------
  # debugging/profiling/testing/logging
  # ----------
  - gdb
  # - hpctoolkit@develop buildtype=debugoptimized ^dyninst@master ^elfutils ~debuginfod
  - hpctoolkit@develop
  - dyninst@master
  - elfutils ~debuginfod
  - papi
  - gperftools
  - googletest
  - protobuf
  - spdlog

  - arch=gh200:
    # GPU support
    - cuda@12.8
    - whip@main

    # Maths
    - nvpl-blas
    - nvpl-lapack
    - nvpl-fft

  - arch=zen2:
    # Maths
    - intel-oneapi-mkl
    - openblas

  - arch=ada:
    # GPU support
    - cuda
    - whip@main

    # Maths
    - intel-oneapi-mkl

  variants:
  - build_type=Release
  - cxxstd=20
  - ~fortran
  - ~examples
  - ~tests
  - ~testing
  - +mpi
  - +cxx
  - +python

  - arch=gh200:
    - +cuda
    - cuda_arch=90
   # - +cuda_uvm
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl

  - arch=zen2:
    - ~cuda
    - ~x11

  - arch=ada:
    - +cuda
    - cuda_arch=89
    - +wrapper
    - ~x11
    - ^[virtuals=gl] egl
